FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0

ARG TARGETARCH

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

COPY --chown=1001:root build/${TARGETARCH}/*-runner /work/httpbucket
RUN chmod +x /work/httpbucket
COPY --chown=1001:root cert.pem /work/cert.pem
COPY --chown=1001:root key.pem /work/key.pem

EXPOSE 8080
EXPOSE 8443
USER 1001

ENTRYPOINT ["./httpbucket", "-Dquarkus.http.host=0.0.0.0"]
