name: CI Build

on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  prepare:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}
      DOCKER_TAG: ${{ steps.version.outputs.DOCKER_TAG }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Get release attributes
        id: version
        run: |
          SUFFIX=""
          DOCKER_TAG=$GITHUB_REF_NAME
          case $GITHUB_REF_NAME in
            main) DOCKER_TAG="latest";;
            alpha) SUFFIX="A";;
            beta) SUFFIX="B";;
          esac
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_OUTPUT
          VERSION=$(grep 'version = ' build.gradle.kts | cut -f 2 -d "\"")$SUFFIX
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if version is used
        run: |
          URL=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/tags/${{ steps.version.outputs.VERSION }}
          CODE=$(curl -s -H "Authorization: Bearer ${{ github.token }}" -o /dev/null -w "%{http_code}" "$URL")
          if [ "$CODE" != 404 ]; then
            echo "Release '${{ steps.version.outputs.VERSION }}' already exists. ($CODE)"
            exit 1
          fi

      - name: Setup ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.8.0/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run linter
        run: ktlint

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false

      - name: Generating self-signed certificate
        run: |
          openssl req \
            -newkey rsa:2048 \
            -new \
            -nodes \
            -x509 \
            -days 2 \
            -keyout key.pem \
            -out cert.pem \
            -subj "/CN=localhost"

      - name: Tests
        run: ./gradlew test

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-report
          path: build/jacoco-report
          if-no-files-found: error
          retention-days: 1

  build-native:
    needs: prepare
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'

      - name: Generating self-signed certificate
        run: |
          openssl req \
            -newkey rsa:2048 \
            -new \
            -nodes \
            -x509 \
            -days 3650 \
            -keyout key.pem \
            -out cert.pem \
            -subj "/C=US/ST=SC/L=Hometown/O=IT/emailAddress=root@localhost/CN=localhost"

      - name: Tests & Build Native Executable
        run: |
          ./gradlew build -Dquarkus.package.jar.enabled=false \
            -Dquarkus.native.enabled=true \
            -Dquarkus.native.compression.level=5 \
            -x test

      - name: Upload Native Binary
        uses: actions/upload-artifact@v7
        with:
          name: native-executable-${{ matrix.arch }}
          path: build/*-runner
          if-no-files-found: error
          retention-days: 1

  publish:
    needs:
      - prepare
      - build-native
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code checkout
        uses: actions/checkout@v6

      - name: Generating self-signed certificate
        run: |
          openssl req \
            -newkey rsa:2048 \
            -new \
            -nodes \
            -x509 \
            -days 3650 \
            -keyout key.pem \
            -out cert.pem \
            -subj "/C=US/ST=SC/L=Hometown/O=IT/emailAddress=root@localhost/CN=localhost"

      - name: Download Jacoco Report
        uses: actions/download-artifact@v8
        with:
          name: jacoco-report
          path: build/jacoco-report

      - name: Download AMD64 Binary
        uses: actions/download-artifact@v8
        with:
          name: native-executable-amd64
          path: build/amd64

      - name: Download ARM64 Binary
        uses: actions/download-artifact@v8
        with:
          name: native-executable-arm64
          path: build/arm64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: src/main/docker/Dockerfile.native-multi-arch
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ github.repository }}:${{ needs.prepare.outputs.VERSION }}
            ${{ github.repository }}:${{ needs.prepare.outputs.DOCKER_TAG }}

      - name: Creating GitHub Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: ${{ needs.prepare.outputs.VERSION }}
          tag_prefix: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.prepare.outputs.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Overwrite Coverage Theme
        run: |
          /bin/cp -rf helpers/jacoco-report/* build/jacoco-report/.
          /bin/cp -f README.md build/jacoco-report/.

      - name: Publishing to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./build/jacoco-report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: httpbucket.testainers.com
